import fs  = require('fs/promises');
import path = require('path');

export function addActivatorFunctionRoleToResources(service: any) {

     const stage = service.provider.stage

     if (typeof service.resources !== 'object') {
          service.resources = {};
     }
     if (typeof service.resources.Resources !== 'object') {
          service.resources.Resources = {};
     }

     service.resources.Resources['ServerlessMagentoActivatorPluginRole'] = {
          Type: 'AWS::IAM::Role',
          Properties: {
               Path: '/',
               RoleName: {
                    'Fn::Join': [
                         '-',
                         [
                              service.service,
                              stage,
                              { Ref: 'AWS::Region' },
                              'activator',
                              'role',
                         ],
                    ],
               },
               AssumeRolePolicyDocument: {
                    Version: '2012-10-17',
                    Statement: [
                         {
                              Effect: 'Allow',
                              Principal: {
                                   Service: [
                                        'lambda.amazonaws.com',
                                   ],
                              },
                              Action: 'sts:AssumeRole',
                         },
                    ],
               },
               Policies: [
                    {
                         PolicyName: {
                              'Fn::Join': [
                                   '-',
                                   [
                                        service.service,
                                        stage,
                                        'serverless-magento',
                                        'acivator',
                                        'policy',
                                   ],
                              ],
                         },
                         PolicyDocument: {
                              Version: '2012-10-17',
                              Statement: [
                                   {
                                        Effect: 'Allow',
                                        Action: [
                                             'logs:CreateLogGroup',
                                             'logs:CreateLogStream',
                                        ],
                                        Resource: [{
                                             'Fn::Sub': `arn:\${AWS::Partition}:logs:\${AWS::Region}:\${AWS::AccountId}:log-group:/aws/lambda/serverless-magento-activator:*`,
                                        }],
                                   },
                                   {
                                        Effect: 'Allow',
                                        Action: [
                                             'logs:PutLogEvents',
                                        ],
                                        Resource: [{
                                             'Fn::Sub': `arn:\${AWS::Partition}:logs:\${AWS::Region}:\${AWS::AccountId}:log-group:/aws/lambda/serverless-magento-activator:*:*`,
                                        }],
                                   },
                                   {
                                        Effect: 'Allow',
                                        Action: [
                                             'ec2:CreateNetworkInterface',
                                             'ec2:DescribeNetworkInterfaces',
                                             'ec2:DetachNetworkInterface',
                                             'ec2:DeleteNetworkInterface',
                                        ],
                                        Resource: '*',
                                   },
                              ],
                         },
                    },
               ],
          },
     };
}

export async function createActivatorFunctionArtifact(region: string, handlerFolder: string) {
     const activatorFunction = `'use strict';
     /** Generated by Serverless magento-serverless **/
          module.exports.activator = async (event, context) => {
          console.log('Activator');
     }`;

     await fs.mkdir(handlerFolder, { recursive: true });
     await fs.writeFile(path.join(handlerFolder, 'index.js'), activatorFunction);

}

export function addActivatorFunctionToService(service: any, activatorConfig: any) {
     service.functions['magentoServerlessActivator'] = {
          description: `Scheduled function which ensures the Magento integration  context is fresh`,
          events: activatorConfig.events,
          handler: activatorConfig.pathHandler.split(path.sep).join(path.posix.sep),
          memorySize: activatorConfig.memorySize,
          name: `${activatorConfig.serviceName}-${activatorConfig.serviceStage}-magentoServerlessActivator`,
    runtime: 'nodejs14.x',
    package: activatorConfig.package,
    timeout: activatorConfig.timeout
  };
}
